/**
  ******************************************************************************
  * @file           : main_example_f401re.c
  * @brief          : Matrix Keypad Example for Nucleo-F401RE
  * @board          : STM32 Nucleo-F401RE
  * @note           : Add this code to your main.c generated by STM32CubeMX/IDE
  ******************************************************************************
  */

#include "main.h"
#include "matrix_stm32.h"
#include "keymap_functions_stm32.h"
#include <stdio.h>

// Set to 1 to enable pin testing mode, 0 for normal operation
#define PIN_TEST_MODE 0

// Example pin configuration for Nucleo-F401RE
// Adjust these to match your wiring
// 
// ROWS (outputs):    PA0, PA1, PA4, PA5
// COLUMNS (inputs):  PB0, PB1, PB4, PB5

int main(void)
{
  // HAL Init
  HAL_Init();
  SystemClock_Config();
  
  // Initialize peripherals (done by CubeMX)
  // MX_GPIO_Init();  // Make sure GPIO clocks are enabled
  // MX_USART2_UART_Init();  // For printf (optional)
  
  printf("\n\n=== Matrix Keypad Driver for STM32 ===\n");
  printf("Board: Nucleo-F401RE\n\n");
  
  // Define pin assignments using the MAKE_PIN macro
  // Format: MAKE_PIN(GPIOx, pin_number)
  const GPIO_Pin_t row_pins[4] = {
      MAKE_PIN(GPIOA, 0),   // Row 0 -> PA0
      MAKE_PIN(GPIOA, 1),   // Row 1 -> PA1
      MAKE_PIN(GPIOA, 4),   // Row 2 -> PA4
      MAKE_PIN(GPIOA, 5)    // Row 3 -> PA5
  };
  
  const GPIO_Pin_t col_pins[4] = {
      MAKE_PIN(GPIOB, 0),   // Col 0 -> PB0
      MAKE_PIN(GPIOB, 1),   // Col 1 -> PB1
      MAKE_PIN(GPIOB, 4),   // Col 2 -> PB4
      MAKE_PIN(GPIOB, 5)    // Col 3 -> PB5
  };
  
  // Initialize the matrix keypad
  matrix_init(row_pins, col_pins);
  printf("Matrix keypad initialized!\n\n");
  
#if PIN_TEST_MODE
  // Pin testing mode - helps you map your keypad
  printf("*** PIN TEST MODE ***\n");
  printf("Press keys to identify which pin maps to which physical position.\n");
  printf("Once you know the mapping, set PIN_TEST_MODE to 0.\n\n");
  
  matrix_test_pins();  // This runs forever
  
#else
  // Initialize function mode system
  keymap_init();
  
  // Normal operation mode
  printf("*** NORMAL OPERATION MODE ***\n");
  printf("Non-blocking keypad scanning active.\n");
  printf("Press F to toggle function mode.\n\n");
  
  KeyEvent event;
  
  while (1)
  {
    // Non-blocking scan - call this as often as possible
    if (matrix_scan(&event)) {
      // Key event detected - only process PRESSED events
      if (event.state == KEY_PRESSED) {
        // Try to process as function mode key
        bool handled = keymap_process_key(event.key);
        
        if (!handled) {
          // Normal mode - just display the key
          printf("Key: 0x%X\n", event.key);
        }
      }
    }
    
    // Optional: add a tiny delay to control scan rate
    // Comment out for maximum speed
    // HAL_Delay(1);  // 1ms delay
  }
#endif
}

// Printf redirection to UART (if using printf for debugging)
#ifdef __GNUC__
int _write(int fd, char *ptr, int len) {
  HAL_UART_Transmit(&huart2, (uint8_t*)ptr, len, HAL_MAX_DELAY);
  return len;
}
#endif

